# Generated by Django 2.1 on 2019-01-23 13:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190123_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 13, 12, 49, 667758, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 13, 12, 49, 725679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$szINxILx$d3286e3a38a7324581794f1f39aa441ed653750e3041dacada5ba64757bccd52', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$maunvNwc$202e882ab7fbf58a8df31d58d1cbf4db01cb8a7e96358d6d0e018c7d584741d8', max_length=1000),
        ),
    ]
