# Generated by Django 2.1 on 2019-01-23 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190123_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 13, 45, 14, 585956, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 13, 45, 14, 645316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$tgChX11e$9a8d6745d256ed3fe5be5c5afa2801edc6829b37be11012601fbe5c82477c985', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$IQbu2hIs$20609b67c39448e37664343fafab179085819ec02e421707a2be266a203e6537', max_length=1000),
        ),
    ]
