# Generated by Django 2.1 on 2019-01-23 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0004_comment'),
        ('accounts', '0004_auto_20190123_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='videos_liked',
            field=models.ManyToManyField(related_name='videos_liked', to='tube.Video'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='videos_unliked',
            field=models.ManyToManyField(related_name='videos_unliked', to='tube.Video'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 14, 51, 16, 676319, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 14, 51, 16, 779601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$hetZiPJ7$ee73250d88d4ea27d105b248b0bd99ae5a79938c9b0045fee3f8fc073ef69fb3', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$gEZhFewU$b73bb4af31d13bd2e588ed637662e74e9515fa741cd316ca926041f1e9f82498', max_length=1000),
        ),
    ]
