# Generated by Django 2.1 on 2019-01-23 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190123_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 14, 57, 43, 327983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 23, 14, 57, 43, 375855, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$FXKtATl1$2f3fdad89f16cdaaee8222bf11d18b00d8de9ae8c4a6db040843a45d68998ef2', max_length=1000),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='videos_liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='videos_liked', to='tube.Video'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='videos_unliked',
            field=models.ManyToManyField(blank=True, null=True, related_name='videos_unliked', to='tube.Video'),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$sCAPaera$e38e1237d3d385d1875e7bc2c03a2cd22997e8bb8a209e2b0a069783230ac4dd', max_length=1000),
        ),
    ]
