# Generated by Django 2.1 on 2019-01-24 10:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190123_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 10, 33, 3, 595721, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 24, 10, 33, 6, 492691, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$FysNVEMd$6d4417f531aa9cf9495c79958fd2fabe9887f44c3ee4b0912fd79d1138b52e4c', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$WjPvsQjY$b7d5c3076471e85b9241bcd7550a0458fa8997db247d4983fcae4311bd1573ad', max_length=1000),
        ),
    ]
