# Generated by Django 2.1 on 2019-01-29 23:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190124_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 29, 23, 8, 59, 314165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 29, 23, 8, 59, 364530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reset_token',
            field=models.CharField(default='pbkdf2:sha256:50000$v1iixHLo$fd712aa9633d7307e778d156b377ad9f83ff0de975526ef18534c57f40f1e5e7', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patron',
            name='email_token',
            field=models.CharField(default='pbkdf2:sha256:50000$9pytIWoO$5f006ee9bcb4d63bd591e27834fb9325f86a16a04da4b2f33798f0ba0c52875f', max_length=1000),
        ),
    ]
